apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mesh-demo
  name: backendb
  labels:
    app: backendb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendb
      version: v1
  template:
    metadata:
      labels:
        app: backendb
        version: v1
#      annotations:
#        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
      - name: backendb
        image: douggynix/istio-demo-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
          protocol: TCP
        env:
          - name: BACKEND_NAME
            value: backendB
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 25
          httpGet:
            path: /
            port: 3001
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: backendb
  namespace: mesh-demo
  labels:
    app: backendb
    service: backendb
spec:
  selector:
    app: backendb
#  type: LoadBalancer
  ports:
  - name: node-tcp
    port: 3001
    protocol: TCP
    