# See more at https://istio.io/docs/reference/config/networking/destination-rule/
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-dest-rule
  namespace: mesh-demo
spec:
  host: frontend
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backenda-dest-rule
  namespace: mesh-demo
spec:
  host: backenda
  subsets:
  - name: v1
    labels:
      version: v1